# Generated by Django 5.2.3 on 2025-06-13 23:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('publication_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Año de publicación')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Cantidad en stock')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de préstamo')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('returned', models.BooleanField(default=False, verbose_name='Devuelto')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Registro de préstamo',
                'verbose_name_plural': 'Registros de préstamo',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
